name: "Build ddnsu with go compile"
on:
  push:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.2"]
    if: ${{ !contains(github.event.head_commit.message, 'ignore build') }}

    steps:
      - uses: actions/checkout@v2
      - name: Install go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod download
      - name: Build ddnsu binaries
        run: make
      - name: Upload artifacts as a release
        uses: softprops/action-gh-release@v2
        with:
          files: "build/*"
          draft: true
